### ISSUE TITLE
Python can't find the identifier module in ensta

### ISSUE THREAD

**Issue by iamdeepak92** [diezo/ensta#1]
```
Traceback (most recent call last):
  File "C:\Users\iamde\Desktop\NewYoutubeScrapperInPython\test.py", line 1, in <module>
    from ensta import Guest
  File "C:\Python310\lib\site-packages\ensta\__init__.py", line 2, in <module>
    from ensta.Host import Host
  File "C:\Python310\lib\site-packages\ensta\Host.py", line 20, in <module>
    from ensta.identifier import IDENTIFIER_USERNAME, IDENTIFIER_USERID
ModuleNotFoundError: No module named 'ensta.identifier'
```

Seems , you are missing some files.

**Comment by diezo** [comment]
Identifier package was completely removed in v1.2, but the pip version was still running on an old version (with some bugs). I've resolved the issue. Please upgrade your package by running:

    pip install ensta --upgrade

Let me know if that solved your issue.

**NOTE:** After upgrading, make sure you've got v1.3 or later.
