### ISSUE TITLE
Status code was: -5

### ISSUE THREAD

**Issue by Elovel** [diezo/Ensta#13]
EVAL:
 from ensta import Host, NewSessionID

sessionid = NewSessionID("*****", "******")

host = Host(sessionid)
status = host.follow("cristiano")

if status is None:
    print("Something went wrong.")
else:
    if status.following:
        print("Following!")
    
    elif status.follow_requested:
        print("Requested to follow!")

OUTPUT:
Traceback (most recent call last):
  File "/home/afxopmpg/public_html/xx/FW/FwHrlot/modules/eval.py", line 26, in eval
    await aexec(cmd, client, message)
  File "/home/afxopmpg/public_html/xx/FW/FwHrlot/modules/eval.py", line 66, in aexec
    return await locals()"__aexec"
  File "", line 4, in aexec
  File "/home/afxopmpg/virtualenv/public_html/xx/3.10/lib/python3.10/site-packages/ensta/Authentication.py", line 19, in NewSessionID
    driver: webdriver.Chrome = webdriver.Chrome(options=options)
  File "/home/afxopmpg/virtualenv/public_html/xx/3.10/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 49, in init
    super().init(
  File "/home/afxopmpg/virtualenv/public_html/xx/3.10/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 51, in init
    self.service.start()
  File "/home/afxopmpg/virtualenv/public_html/xx/3.10/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 97, in start
    self.assert_process_still_running()
  File "/home/afxopmpg/virtualenv/public_html/xx/3.10/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/afxopmpg/.cache/selenium/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: -5

**Comment by diezo** [comment]
Looks like chromium is not installed on your os. Install it by running:
```
sudo apt install -y chromium browser
```

Let me know if that solved your issue.
