### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by Viven763** [diezo/Ensta#15]
```
from ensta import Guest

guest = Guest()
profile = guest.profile("cristiano")

if profile is None:
    print("Something went wrong.")
else:
    print(profile.biography)
    print(profile.follower_count)
    print(profile.following_count)
    
   
```

And this issue

```
Traceback (most recent call last):
  File "/Users/vivenlmao/Desktop/sergey/insta_hash_bot/test.py", line 1, in <module>
    from ensta import Guest
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ensta/__init__.py", line 1, in <module>
    from ensta.Guest import Guest
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ensta/Guest.py", line 4, in <module>
    from .lib.Commons import (
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ensta/lib/__init__.py", line 1, in <module>
    from .Commons import (
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ensta/lib/Commons.py", line 72, in <module>
    def format_identifier(identifier: str | int) -> str:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**Comment by diezo** [comment]
Just upgrade your python version from [here](https://www.python.org/downloads/release/python-3114/) and everything will work fine.
