### ISSUE TITLE
substring not found

### ISSUE THREAD

**Issue by owckie** [diezo/Ensta#32]
Hey!

I'm using the same code as mentioned in my previous issue. As before, it has been working with no issues for a few hours and then this error began popping up after I've renewed my sessionID after my previous one expired (side note: Is there a way to add a notification when your sessionID has expired and you need to grab a new one from the browser?).

```
(venv) z@z-MacBook-Pro InstagramUnfollow % python3 unfollow.py
Traceback (most recent call last):
  File "/Users/z/Documents/Code/InstagramUnfollow/unfollow.py", line 93, in <module>
    host = BaseHost(sessionID)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/z/Documents/Code/InstagramUnfollow/venv/lib/python3.11/site-packages/ensta/BaseHost.py", line 57, in __init__
    update_app_id(self)
  File "/Users/z/Documents/Code/InstagramUnfollow/venv/lib/python3.11/site-packages/ensta/lib/Commons.py", line 11, in update_app_id
    app_id_first_occurrence = self.homepage_source.index(app_id_occurrence_string)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: substring not found
```

**Comment by diezo** [comment]
Hey. I've fixed the bug. Does your code work now?
