### ISSUE TITLE
Too many redirects (exceeded 30)

### ISSUE THREAD

**Issue by pama1999** [diezo/Ensta#49]
This happens sometimes while looping through the followings of a user and the gathering the info of that user, in the gathering process after scraping around 10 I seem to get this error:

![image](https://github.com/diezo/Ensta/assets/42815276/32b54907-8837-4004-8624-b6ac7da249a4)

**Comment by pama1999** [comment]
tried to maybe fix it with a sleep delay but doesnt seem to work as well:

def get_user_info(self, username):
        try:
            return self.host.profile(username)
        except requests.exceptions.TooManyRedirects:
            sleep(10)
            return self.host.profile(username)

**Comment by pama1999** [comment]
compelete traceback:

Traceback (most recent call last):
  File "f:\3. Fun Projects\InfluSpy\Testing\ensta_test.py", line 34, in get_user_info
    return self.host.profile(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\3. Fun Projects\InfluSpy\venv\Lib\site-packages\ensta\SessionHost.py", line 556, in profile
    return self.guest.profile(username, __session__=self.request_session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\3. Fun Projects\InfluSpy\venv\Lib\site-packages\ensta\Guest.py", line 103, in profile
    http_response: requests.Response = session.get(
                                       ^^^^^^^^^^^^
  File "f:\3. Fun Projects\InfluSpy\venv\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\3. Fun Projects\InfluSpy\venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\3. Fun Projects\InfluSpy\venv\Lib\site-packages\requests\sessions.py", line 725, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "f:\3. Fun Projects\InfluSpy\venv\Lib\site-packages\requests\sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Parham\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Parham\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\Parham\.vscode\extensions\ms-python.python-2023.22.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\Parham\.vscode\extensions\ms-python.python-2023.22.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\Parham\.vscode\extensions\ms-python.python-2023.22.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\Parham\.vscode\extensions\ms-python.python-2023.22.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Parham\.vscode\extensions\ms-python.python-2023.22.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\Parham\.vscode\extensions\ms-python.python-2023.22.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "f:\3. Fun Projects\InfluSpy\Testing\ensta_test.py", line 54, in <module>
    user_info = account.get_user_info(user.username)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\3. Fun Projects\InfluSpy\Testing\ensta_test.py", line 37, in get_user_info
    return self.host.profile(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\3. Fun Projects\InfluSpy\venv\Lib\site-packages\ensta\SessionHost.py", line 556, in profile
    return self.guest.profile(username, __session__=self.request_session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\3. Fun Projects\InfluSpy\venv\Lib\site-packages\ensta\Guest.py", line 103, in profile
    http_response: requests.Response = session.get(
                                       ^^^^^^^^^^^^
  File "f:\3. Fun Projects\InfluSpy\venv\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\3. Fun Projects\InfluSpy\venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\3. Fun Projects\InfluSpy\venv\Lib\site-packages\requests\sessions.py", line 725, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "f:\3. Fun Projects\InfluSpy\venv\Lib\site-packages\requests\sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by diezo** [comment]
are you able to fetch 10 or a few users every time you run the script? or it just no longer works?

**Comment by pama1999** [comment]
do you have another commuincation channel? like Discord? if so kindly add me on discord for the source: @pama021

**Comment by diezo** [comment]
i've sent you a request. i'm on discord as @notdiezo

**Comment by pama1999** [comment]
seems like this error is realted to the accs getting locked or flagged

![image](https://github.com/diezo/Ensta/assets/42815276/b03ba25b-085a-4b4c-8eab-632b73ba529f)
