### ISSUE TITLE
Using ensta with flask app

### ISSUE THREAD

**Issue by OlguD** [diezo/Ensta#50]
**I have this flask app, it runs perfectly in my local computer, but when I want to run same code in the server it gives error. I have ensta-session.txt file in the server and in my local computer for authantication** 

```
from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from ensta import Host, SessionHost
import json
import pymongo
from pymongo import MongoClient

app = Flask(__name__)
client = MongoClient(DB_URL)
limiter = Limiter(get_remote_address, app=app, default_limits=["15 per hour"])


db = client['users']
collection = db['user_followers']

@app.route('/login', methods=['POST'])
@limiter.limit("10 per 5 minutes")
def login():
    """
    this function takes "username" & "password", and returns session_data which is used to perform authenticated requests
    """
    username = request.form.get('username')
    password = request.form.get('password')

    try:
        host = Host(username, password)
        # login successful

        # Set a per-user rate limit for subsequent requests
        #limit_key = f"login:{username}"
        #limiter.reset(limit_key)  # Reset the limit for the user

        return {"status": "ok", "session_data": host.session_data}

    except Exception as e:
        # login failed
        return {"status": "fail", "message": str(e)}


@app.route('/useSessionCookie', methods=['GET', 'POST'])
def profile_data():
    with open('ensta-session.txt', 'r') as file:
        session_data_str = file.read()

    username = request.args.get('username')


    #if username == session_data_str['username']:
    host = SessionHost(session_data_str)
    profile = host.profile(username)

    # Kullanıcının takipçi listesini al
    followers_list = getFollowerList(host, username)
    # Veri setine takipçileri ekle.
    saveUserFollowerToDatabase(username, followers_list)

    posts_url = []
    posts = profile.raw

    for post_key, post_value in posts.items():
        if post_key == 'edge_owner_to_timeline_media':
            for node in posts[post_key]['edges']:
                # for döngüsü içinde node değerine sahibiz
                post_id = host.get_post_id(f"https://www.instagram.com/p/{node['node']['shortcode']}")
                likers = host.likers(post_id)
                post_info = {
                    'url': node['node']['display_url'],
                    'comment_count': node['node']['edge_media_to_comment']['count'],
                    'likers': [{'username': user.username, 'profile_picture_url': user.profile_picture_url} for user in likers.users],
                    'caption': [texts['node']['text'] for texts in node['node']['edge_media_to_caption']['edges']]
                }
                posts_url.append(post_info)


    wanted_informations = {
        'full_name': profile.full_name,
        'biography': profile.biography,
        'biography_link': profile.biography_links,
        'follower': profile.follower_count,
        'following': profile.following_count,
        'profile_picture_url_hd': profile.profile_picture_url_hd,  
        'post_info': posts_url, # Gives post_link, post_comment_count, post_likers, post_caption
        'total_post_count': profile.total_post_count,
        'unfollowed_users' : getUnfollowedUser(host, username)
    }
    
    #return {"status": "ok", "profile": profile.__dict__} Returns all the features
    return {'status': 'ok', 'profile': wanted_informations}
    # else:
    #     return {"status": "fail", "message": "Invalid username"}


def saveUserFollowerToDatabase(username, followers):
    user_data = collection.find_one({'username': username})

    if user_data is None:
        user_data = {'username': username, 'followers': followers}
        collection.insert_one(user_data)
    else:
        existing_followers = user_data.get('followers', [])
        existing_followers.extend(followers)
        collection.update_one(
            {'username': username},
            {'$set': {'followers': existing_followers}}
        )


def getFollowerList(host, username):
    follower_list = host.followers(username)
    return [user.username for user in follower_list]


def getUnfollowedUser(host, username):
    user_data = collection.find_one({"username": username})
    if user_data and "followers" in user_data:
        old_follower_list = user_data["followers"]
    else:
        old_follower_list = []
        return {'status': 'fail', 'error': 'user not found or user_data not found in db'}
    

    new_follower_list = getFollowerList(host, username)

    old_follower_set = set(old_follower_list)
    new_follower_set = set(new_follower_list)

    unfollowed_users = old_follower_set - new_follower_set

    return list(unfollowed_users)


if __name__ == '__main__':
    app.run(debug=True, port=8090)
```

**### API TEST FILE**
```
login_url = f"{base_url}/login"
login_data = {'username': 'xxxxxxx', 'password': 'xxxxxxxx'}

response = requests.post(login_url, data=login_data)
if response.json()['status'] == 'ok':
    profile_url = f'{base_url}/useSessionCookie'
    profile_data = {'username': 'xxxxxxxx'}
    profile_response = requests.get(profile_url, params=profile_data)
    json_data = profile_response.json()
    print(json.dumps(json_data, indent=4))
else:
    print("Login failed. Check your credentials.")
```    
    
```
    212.108.151.168 - - [09/Dec/2023 14:41:47] "GET /useSessionCookie?username=xxxxxxxx HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/root/api/API/venv/lib/python3.11/site-packages/ensta/SessionHost.py", line 334, in followers
    is_possible_scammer=each_item["is_possible_scammer"]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'is_possible_scammer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/api/API/venv/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/api/API/venv/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/api/API/venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/api/API/venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/api/API/venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/api/API/venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/api/API/app.py", line 54, in profile_data
    followers_list = getFollowerList(host, username)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/api/API/app.py", line 113, in getFollowerList
    return [user.username for user in follower_list]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/api/API/app.py", line 113, in <listcomp>
    return [user.username for user in follower_list]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/api/API/venv/lib/python3.11/site-packages/ensta/SessionHost.py", line 338, in followers
    raise APIError()
ensta.lib.Exceptions.APIError: None
```

**Comment by diezo** [comment]
user should pass session data everytime he wishes to make an authenticated request. you need to fetch ```session_data_str``` from cookies or headers and not ```ensta-session.txt``` file.

there's no need to use the session file now.

**Comment by OlguD** [comment]
When I only want to use this code it gives an error :
```
profile_url = f'{base_url}/useSessionCookie'
profile_data = {'username': 'fegimib190'}
profile_response = requests.get(profile_url, params=profile_data)
json_data = profile_response.json()
print(json.dumps(json_data, indent=4))
```

**Error in the server**
```
212.108.151.168 - - [09/Dec/2023 14:52:04] "GET /useSessionCookie?username=fegimib190 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/root/api/API/venv/lib/python3.11/site-packages/ensta/SessionHost.py", line 334, in followers
    is_possible_scammer=each_item["is_possible_scammer"]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'is_possible_scammer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/api/API/venv/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/api/API/venv/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/api/API/venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/api/API/venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/api/API/venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/api/API/venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/api/API/app.py", line 54, in profile_data
    followers_list = getFollowerList(host, username)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/api/API/app.py", line 113, in getFollowerList
    return [user.username for user in follower_list]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/api/API/app.py", line 113, in <listcomp>
    return [user.username for user in follower_list]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/api/API/venv/lib/python3.11/site-packages/ensta/SessionHost.py", line 338, in followers
    raise APIError()
ensta.lib.Exceptions.APIError: None
```


In my terminal:
```
(venv) (base) olgudegirmenci@Olgu-MacBook-Pro API % python api_test.py
Traceback (most recent call last):
  File "/Users/olgudegirmenci/miniconda3/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olgudegirmenci/miniconda3/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olgudegirmenci/miniconda3/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olgudegirmenci/miniconda3/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by diezo** [comment]
this issue has already been fixed earlier. just update ensta using: ```pip install ensta --upgrade```

**Comment by OlguD** [comment]
Oh, I've upgraded earlier but when I upgrade it again it fixed thanks.

**Comment by OlguD** [comment]
> this issue has already been fixed earlier. just update ensta using: `pip install ensta --upgrade`
