### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Dodutils** [diezo/Ensta#51]
Hello,

I just installed Ensta fine but if I want to test on of the examples I get a TypeError :

Traceback (most recent call last):
  File "test2.py", line 1, in <module>
    from ensta import Host
  File "/home/test/.local/lib/python3.8/site-packages/ensta/__init__.py", line 1, in <module>
    from ensta.Guest import Guest
  File "/home/test/.local/lib/python3.8/site-packages/ensta/Guest.py", line 6, in <module>
    from .containers.Profile import Profile
  File "/home/test/.local/lib/python3.8/site-packages/ensta/containers/__init__.py", line 2, in <module>
    from .Profile import Profile
  File "/home/test/.local/lib/python3.8/site-packages/ensta/containers/Profile.py", line 5, in <module>
    class Profile:
  File "/home/test/.local/lib/python3.8/site-packages/ensta/containers/Profile.py", line 24, in Profile
    pronouns: list[str] = None,
TypeError: 'type' object is not subscriptable

Any idea ?

Regards.

**Comment by diezo** [comment]
you just have to download the latest version of python on your system from (here)[https://www.python.org/downloads/] and you should be good to go


also, don't forget to star this repository if you like ensta, so that other developers can know about it as well.

thanks

**Comment by arijit4** [comment]
@diezo mailed you for a specific need. Can you kindly check/

**Comment by Dodutils** [comment]
Upgraded from Python 3.8 to 3.10 now it works thanks

**Comment by diezo** [comment]
@arijit4 i've read your mail. i think the best way is to connect on discord. my discord: @notdiezo

thankyou
