### ISSUE TITLE
User recognising problems

### ISSUE THREAD

**Issue by dcurim** [diezo/Ensta#58]
While i was trying to get the followers and follows from an account i received this error, i am not sure if it's a problem from the library or what but i share it here to receive some feedback:

Traceback (most recent call last):
  File "C:\Python\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python310\lib\site-packages\ensta\Guest.py", line 111, in profile
    response_json: dict = http_response.json()
  File "C:\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\desktop\insta project\main.py", line 124, in <module>
    funciones()
  File "C:\desktop\insta project\main.py", line 115, in funciones
    for user in seguidores:
  File "C:\Python\Python310\lib\site-packages\ensta\SessionHost.py", line 261, in followers
    conversion_success, identifier = self._identifier(identifier, UID)
  File "C:\Python\Python310\lib\site-packages\ensta\SessionHost.py", line 457, in _identifier
    user_id = self.get_uid(identifier)
  File "C:\Python\Python310\lib\site-packages\ensta\SessionHost.py", line 570, in get_uid
    return self.guest.get_uid(username, __session__=self.request_session)
  File "C:\Python\Python310\lib\site-packages\ensta\Guest.py", line 181, in get_uid
    response: Profile | None = self.profile(username, __session__)
  File "C:\Python\Python310\lib\site-packages\ensta\Guest.py", line 177, in profile
    raise NetworkError("HTTP Response is not a valid JSON.")
ensta.lib.Exceptions.NetworkError: HTTP Response is not a valid JSON.

**Comment by diezo** [comment]
are you comfortable sharing your code? it'll help me get more context on the issue.

**Comment by dcurim** [comment]
> are you comfortable sharing your code? it'll help me get more context on the issue.

could i contact you throw discord or telegram or any social media so i can share it to you?

**Comment by diezo** [comment]
you can share the code with me on discord: **@notdiezo**

**Comment by dcurim** [comment]
> you can share the code with me on discord: **@notdiezo**

accept friend request so i can send links to you when you are able to
