### ISSUE TITLE
ModuleNotFoundError: No module named 'Cryptodome'

### ISSUE THREAD

**Issue by UsmanLiaqat404** [diezo/Ensta#69]
C:\Users\chusm\Downloads\ww> `python -V`
Python 3.12.1

C:\Users\chusm\Downloads\ww>` python .\main.py`
Traceback (most recent call last):
  File "C:\Users\chusm\Downloads\ww\main.py", line 1, in <module>
    from ensta import Guest
  File "C:\Users\chusm\AppData\Local\Programs\Python\Python312\Lib\site-packages\ensta\__init__.py", line 3, in <module>
    from ensta.Host import Host
  File "C:\Users\chusm\AppData\Local\Programs\Python\Python312\Lib\site-packages\ensta\Host.py", line 5, in <module>
    from .Authentication import new_session_id
  File "C:\Users\chusm\AppData\Local\Programs\Python\Python312\Lib\site-packages\ensta\Authentication.py", line 10, in <module>
    from .PasswordEncryption import PasswordEncryption
  File "C:\Users\chusm\AppData\Local\Programs\Python\Python312\Lib\site-packages\ensta\PasswordEncryption.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
ModuleNotFoundError: No module named 'Cryptodome'

**Comment by OlguD** [comment]
try this: `pip install pycryptodomex`
this should solve your error

**Comment by diezo** [comment]
pycryptodome has been replaced by cryptography in the latest release.

please update ensta. everything should work fine.
