### ISSUE TITLE
Showing error on Railway.app deployment

### ISSUE THREAD

**Issue by mohaimenulislamshawon** [diezo/Ensta#72]
**Errors**

Traceback (most recent call last):

File "main.py", line 7, in <module>

from ensta import Host

File "/opt/venv/lib/python3.8/site-packages/ensta/__init__.py", line 1, in <module>

from ensta.Guest import Guest

File "/opt/venv/lib/python3.8/site-packages/ensta/Guest.py", line 6, in <module>

from .containers.Profile import Profile

File "/opt/venv/lib/python3.8/site-packages/ensta/containers/__init__.py", line 2, in <module>

from .Profile import Profile

File "/opt/venv/lib/python3.8/site-packages/ensta/containers/Profile.py", line 5, in <module>

class Profile:

File "/opt/venv/lib/python3.8/site-packages/ensta/containers/Profile.py", line 24, in Profile

pronouns: list[str] = None,

TypeError: 'type' object is not subscriptable

**Comment by diezo** [comment]
you just need to upgrade to Python 3.10 or later.
