### ISSUE TITLE
blocks the email

### ISSUE THREAD

**Issue by tulliodeans** [diezo/Ensta#98]
Good afternoon, Diezo! I have a small problem that every account I try to log into using "mobile = Mobile(username, password)", only returns email confirmation. I log into the account through the browser, it is normal, when I run the code it blocks the email. Can you fix it?

**Comment by tulliodeans** [comment]
Traceback (most recent call last):
  File "c:\Users\patiwifo\API.py", line 46, in <module>
    mobile = Mobile(username, password)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patiwifo\AppData\Local\Programs\Python\Python312\Lib\site-packages\ensta\Mobile.py", line 51, in __init__
    self.refresh_credentials(
  File "C:\Users\patiwifo\AppData\Local\Programs\Python\Python312\Lib\site-packages\ensta\Mobile.py", line 82, in refresh_credentials
    self.credentials = Credentials(
                       ^^^^^^^^^^^^
  File "C:\Users\patiwifo\AppData\Local\Programs\Python\Python312\Lib\site-packages\ensta\Credentials.py", line 73, in __init__
    self.login(identifier, password, save_file)
  File "C:\Users\patiwifo\AppData\Local\Programs\Python\Python312\Lib\site-packages\ensta\Credentials.py", line 143, in login
    raise AuthenticationError(
ensta.lib.Exceptions.AuthenticationError: Login failed with given credentials.
Error: "unknown"
Message: "challenge_required"
